### ISSUE TITLE
Couldn't find key toValue in dynamic object

### ISSUE THREAD

**Issue by bitshadow** [antonKalinin/react-native-image-view#4] opened 2018-01-18 05:58 UTC
"react-native": "^0.49.3",
"react": "^16.0.0-beta.5",

<img width="301" alt="screen shot 2018-01-20 at 6 22 16 pm" src="https://user-images.githubusercontent.com/574802/35183874-e4c899a0-fe12-11e7-917f-063fb9322f9c.png">

**Comment by antonKalinin** [comment] 2018-01-18 12:49
Hi, @bitshadow Could you give me a little more information about error: when it occurs? with mounting a component with `ImageView` or when you try to open a modal? I have't faced with such error at a lot during the development. But I noticed that I developed this module on react-native v0.51 and maybe something have been change sing 0.49. Try to discover this issue today-tomorrow. Thanks.

**Comment by bitshadow** [comment] 2018-01-18 13:30
@antonKalinin 

Error happens when interacting inside the modal.
This is what I did
1. Clicked on the Image.
2. After the first interaction in the modal it show the error.

```
handleImagePress = () => {
    this.setState({
      isLightboxOn: true,
    });
};

handleOnClose = () => {
    this.setState({ isLightboxOn: false });
};

render() {
        ...
        <TouchableOpacity onPress={this.handleImagePress}>
          <Image
            source={require('./assets/test.jpg')}
            style={{ height: imageHeight, width: width }}
          />
        </TouchableOpacity>
        <ImageView
          source={this.getVoucherImage()}
          isVisible={isLightboxOn}
          onClose={this.handleOnClose}
          imageWidth={width * 2}
          imageHeight={imageHeight * 2}
          animationType="fade"
        />
}
```

**Comment by bitshadow** [comment] 2018-01-19 09:27
@antonKalinin Its only happening for Android. In iOS works fine.

**Comment by antonKalinin** [comment] 2018-01-20 12:43
@bitshadow Hi again, cant reproduce your problem: I noticed that you load an image from local assets and thought it creates a problem, but no. So trying to find same conditions as you have. Could you tell me if you run expo example from repo on your android will you get this error? Do you run on emulator or device?

**Comment by bitshadow** [comment] 2018-01-20 13:20
@antonKalinin I just ran the example side by side in Android emulator and I was able to reproduce it by removing `renderFooter` prop from `ImageView` in the example. Sample that I have provided above doesn't not have `renderFooter` which is causing the issue. Let me know if you need more help.

**Comment by antonKalinin** [comment] 2018-01-21 19:54
@bitshadow I removed `renderFooter` and run example on Nexus 5, everything seems okay. Maybe we have different versions of android? If you have android device, can you test expo example?

**Comment by adamwan92** [comment] 2018-01-23 04:54
I am also having experiencing this error. @bitshadow What did you do to remedy this?

**Comment by bitshadow** [comment] 2018-01-23 05:00
@adamwan92 I added empty view in `renderFooter={() => <View />}` and it fixed it.

@antonKalinin I think if you try running the app without using expo (with `create-react-native-app`). You might be able to reproduce this issue. Let me know if you like to have a app for it. I can create one for you if needed.

**Comment by bitshadow** [comment] 2018-01-23 08:17
@antonKalinin I have created a repo which reproduces this issue. Let me know if that helps. (I think `title + renderFooter` props are the problems)
https://github.com/bitshadow/react-native-image-view-example

**Comment by antonKalinin** [comment] 2018-01-23 10:03
@bitshadow Thanks for example! I finally realised that I have title prop, so footer was rendering always. I fixed this issue by checking footer height: version [1.2.5] (https://github.com/antonKalinin/react-native-image-view/releases/tag/v1.2.5)

Closing this issue, fell free to reopen it if any problems occur.

**Closed by antonKalinin** 2018-01-23 10:03 UTC
